export interface Form {
    id?: number
    minPercent:number
    damagedArea:number
    externalDecay:number
    cankerLesion:number
    fruitSpots:number
    cropHist:number
    fruitingBodies:number
    fruitPods:number
    germination:number
    hail:number
    intDiscolor:number
    leafMalf:number
    leafMild:number
    leafShread:number
    leafSpotsHalo:number
    leafSpotsSize:number
    leafSpotsMarg:number
    leaves:number
    lodging:number
    moldGrowth:number
    mycelium:number
    plantGrowth:number
    plantStand:number
    precip:number
    roots:number
    sclerotia:number
    seedDiscolor:number
    severity:number
    seedTmt:number
    stem:number
    stemCanker:number
    months:number
    temps:number
}
